### ISSUE TITLE
第一步 main.py 执行后configs中没有fields_configs字段

### ISSUE THREAD

**Issue by Mcnotbag** [SeeFlowerX/frida-protobuf#1]
seeFlower yyds!
请问大佬， 55m+5bqm6LS05ZCn是用的 com.squareup.wire  ， fields_configs 读不出来是为何

**Comment by SeeFlowerX** [comment]
因为它是用的`com.squareup.wire.ProtoField`而不是`com.squareup.wire.WireField`，脚本没有针对`ProtoField`做处理，所以fields_config就是空了。

**Comment by SeeFlowerX** [comment]
已支持`ProtoField`注解的解析转换，命令示例可以查看README，但没有进行实际数据解析测试。

![image](https://user-images.githubusercontent.com/70688581/144701291-4c839007-0101-44c3-bb71-c26340f41b74.png)

**Comment by SeeFlowerX** [comment]
如果仍然有疑问，请重新打开此issue。
