### ISSUE TITLE
XXX is not defined.

### ISSUE THREAD

**Issue by wttnb911** [SeeFlowerX/frida-protobuf#4]
pyproto/tbclient.ThreadInfo.proto:41:1: File recursively imports itself: pyproto/tbclient.ThreadInfo.proto -> pyproto/tbclient.VideoActive.proto -> pyproto/tbclient.ThreadInfo.proto
pyproto/tbclient.VideoActive.proto:5:1: Import "pyproto/tbclient.ThreadInfo.proto" was not found or had errors.
pyproto/tbclient.VideoActive.proto:15:14: "ThreadInfo" is not defined.
pyproto/tbclient.ThreadInfo.proto:41:1: Import "pyproto/tbclient.VideoActive.proto" was not found or had errors.
pyproto/tbclient.ThreadInfo.proto:158:14: "VideoActive" is not defined.
pyproto/tbclient.HotThreadList.DataRes.proto:5:1: Import "pyproto/tbclient.ThreadInfo.proto" was not found or had errors.
pyproto/tbclient.HotThreadList.DataRes.proto:11:14: "tbclient.ThreadInfo" is not defined.

**Comment by wttnb911** [comment]
> 
这个是循环引用的原因吗

**Comment by SeeFlowerX** [comment]
`recursively imports` 看错误提示是这样，需要尝试自行修改下proto文件。
